# Generated by Django 2.2.4 on 2021-01-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Users_that_liked', models.ManyToManyField(related_name='Wishes_liked', to='login_app.User')),
                ('user_that_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes_of_user', to='login_app.User')),
            ],
        ),
    ]
