# Generated by Django 2.2.4 on 2021-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
