# Generated by Django 2.2.4 on 2021-01-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_wish_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='desc',
            field=models.TextField(default='Default Descripton'),
            preserve_default=False,
        ),
    ]
