# Generated by Django 2.2.4 on 2021-01-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('wish_app', '0003_wish_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='Users_that_liked',
        ),
        migrations.AddField(
            model_name='wish',
            name='users_that_liked',
            field=models.ManyToManyField(related_name='wishes_liked', to='login_app.User'),
        ),
    ]
